# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb44a3e6cefb5887e6cbc354ee5b8be8418a216de0fd711660de6379148e2f69721a36501d3f2a9045634a489c4f7364a4b1613975e32bbc1b1d698d8c31934d

test:
  secret_key_base: 3b02bb0fe0d6d2df2aa7c54813e9a309fc0a6a60c60ba542cde81da4012ee947849239db524139e73095e0ba33d33665a767bc129abf76a366b1db6a5a4b5182

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
